name: sansgen
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
#  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  gap: ^3.0.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  flutter_snake_navigationbar: ^0.6.1
  loading_animation_widget: ^1.2.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  flutter_rating_bar: ^4.0.1
  octo_image: ^2.0.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  circular_countdown_timer: ^0.2.3
  hidable: ^1.0.6
  flutter_popup_menu_button: ^0.0.1+5
  pinput: ^5.0.0
  sks_ticket_view: ^1.0.0
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.13
  audio_video_progress_bar: ^2.0.3
  rxdart: ^0.28.0
  just_audio_mpv: ^0.1.7
  audio_session: ^0.1.21
  url_launcher: ^6.3.0
  scroll_loop_auto_scroll: ^0.0.5
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.1
  collection: ^1.18.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env